# Generated by Django 5.2.1 on 2025-08-21 00:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='default_avatar_image', max_length=255, verbose_name='avatar_image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default_post_image', max_length=255, verbose_name='post_image'),
        ),
    ]
