# Generated by Django 5.2.1 on 2025-08-21 00:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_avatar_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dlupcjis0/image/upload/v1746993289/default_post_image.jpg', max_length=255, verbose_name='post_image'),
        ),
    ]
