# Generated by Django 5.2.1 on 2025-08-21 00:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default_post_image', max_length=255, verbose_name='post_image'),
        ),
    ]
